import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Home1</Link>
        </li>
        <li>
          <Link to="/store">Store</Link>
        </li>
        <li>
          <Link to="/typography">Typography</Link>
        </li>
        <li>
          <Link to="/colorguidance">ColorGuidance</Link>
        </li>
        <li>
          <Link to="/elevation">Elevation</Link>
        </li>
        <li>
          <Link to="/elements">Elements</Link>
        </li>
        <li>
          <Link to="/layoutbreakpoints">LayoutBreakpoints</Link>
        </li>
        <li>
          <Link to="/bottomappbars">Bottomappbars</Link>
        </li>
        <li>
          <Link to="/bottomsheets">Bottomsheets</Link>
        </li>
        <li>
          <Link to="/buttons">Buttons</Link>
        </li>
        <li>
          <Link to="/cards">Cards</Link>
        </li>
        <li>
          <Link to="/checkboxes">Checkboxes</Link>
        </li>
        <li>
          <Link to="/chips">Chips</Link>
        </li>
        <li>
          <Link to="/datepicker">Datepicker</Link>
        </li>
        <li>
          <Link to="/dialogs">Dialogs</Link>
        </li>
        <li>
          <Link to="/dividers">Dividers</Link>
        </li>
        <li>
          <Link to="/fabs">FABs</Link>
        </li>
        <li>
          <Link to="/iconbuttons">Iconbuttons</Link>
        </li>
        <li>
          <Link to="/lists">Lists</Link>
        </li>
        <li>
          <Link to="/menu">Menu</Link>
        </li>
        <li>
          <Link to="/navigationbars">Navigationbars</Link>
        </li>
        <li>
          <Link to="/navigationdrawer">Navigationdrawer</Link>
        </li>
        <li>
          <Link to="/radiobuttons">Radiobuttons</Link>
        </li>
        <li>
          <Link to="/segmentedbuttons">Segmentedbuttons</Link>
        </li>
        <li>
          <Link to="/sliders">Sliders</Link>
        </li>
        <li>
          <Link to="/snackbars">Snackbars</Link>
        </li>
        <li>
          <Link to="/switch">Switch</Link>
        </li>
        <li>
          <Link to="/tabs">Tabs</Link>
        </li>
        <li>
          <Link to="/textfields">TextFields</Link>
        </li>
        <li>
          <Link to="/timepicker">Timepicker</Link>
        </li>
        <li>
          <Link to="/topappbars">Topappbars</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
